services:
  Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Export\CliExportAction:
    arguments:
      - '%kernel.project_dir%'
      - '%sulu_translations.export_format%'

  Phpro\SuluTranslationsBundle\Domain\Action\ExportAction: '@Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Export\CliExportAction'