services:
  Phpro\SuluTranslationsBundle\Domain\Command\ExportHandler:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Time\Clock'
      - '@Phpro\SuluTranslationsBundle\Domain\Action\ExportAction'
      - '@Phpro\SuluTranslationsBundle\Domain\Events\EventDispatcher'

  Phpro\SuluTranslationsBundle\Domain\Command\DeleteHandler:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Time\Clock'
      - '@Phpro\SuluTranslationsBundle\Domain\Repository\TranslationRepository'
      - '@Phpro\SuluTranslationsBundle\Domain\Events\EventDispatcher'

  Phpro\SuluTranslationsBundle\Domain\Command\UpdateHandler:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Time\Clock'
      - '@Phpro\SuluTranslationsBundle\Domain\Repository\TranslationRepository'
      - '@Phpro\SuluTranslationsBundle\Domain\Events\EventDispatcher'

  Phpro\SuluTranslationsBundle\Domain\Command\WriteHandler:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Time\Clock'
      - '@Phpro\SuluTranslationsBundle\Domain\Repository\TranslationRepository'
      - '@Phpro\SuluTranslationsBundle\Domain\Events\EventDispatcher'