services:
  Phpro\SuluTranslationsBundle\Presentation\Console\SetupTranslationsTableCommand:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\Schema\SetupTranslationsTable'
    tags:
      - console.command