services:
  Phpro\SuluTranslationsBundle\Presentation\Controller\Admin\ListController:
    arguments:
      - '@serializer'
      - '@sulu_core.list_rest_helper'
      - '@Phpro\SuluTranslationsBundle\Domain\Query\FetchTranslations'
    tags:
      - { name: 'controller.service_arguments' }
      - { name: 'sulu.context', context: 'admin' }

  Phpro\SuluTranslationsBundle\Presentation\Controller\Admin\FetchController:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Query\FetchTranslation'
      - '@Phpro\SuluTranslationsBundle\Domain\Serializer\TranslationSerializer'
    tags:
      - { name: 'controller.service_arguments' }
      - { name: 'sulu.context', context: 'admin' }

  Phpro\SuluTranslationsBundle\Presentation\Controller\Admin\UpdateController:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Command\UpdateHandler'
      - '@Phpro\SuluTranslationsBundle\Domain\Query\FetchTranslation'
      - '@Phpro\SuluTranslationsBundle\Domain\Serializer\TranslationSerializer'
    tags:
      - { name: 'controller.service_arguments' }
      - { name: 'sulu.context', context: 'admin' }

  Phpro\SuluTranslationsBundle\Presentation\Controller\Admin\ExportController:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Command\ExportHandler'
    tags:
      - { name: 'controller.service_arguments' }
      - { name: 'sulu.context', context: 'admin' }