services:
  Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\Schema\SetupTranslationsTable:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\DatabaseConnectionManager'

  Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\Mapper\TranslationMapper: ~

  Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\DatabaseConnectionManager:
    arguments:
      - '@translation.provider_collection'
      - '@Doctrine\Persistence\ManagerRegistry'
    lazy: true