services:
  Phpro\SuluTranslationsBundle\Infrastructure\Psr\PsrEventDispatcher:
    arguments:
      - '@Psr\EventDispatcher\EventDispatcherInterface'
  Phpro\SuluTranslationsBundle\Domain\Events\EventDispatcher: '@Phpro\SuluTranslationsBundle\Infrastructure\Psr\PsrEventDispatcher'

