services:
  Phpro\SuluTranslationsBundle\Domain\Query\FetchTranslation:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Repository\TranslationRepository'
  Phpro\SuluTranslationsBundle\Domain\Query\FetchTranslations:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Repository\TranslationRepository'