services:
  Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\Repository\DoctrineTranslationRepository:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\DatabaseConnectionManager'
      - '@Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\Mapper\TranslationMapper'
  Phpro\SuluTranslationsBundle\Domain\Repository\TranslationRepository: '@Phpro\SuluTranslationsBundle\Infrastructure\Doctrine\Repository\DoctrineTranslationRepository'