services:
  phpro_translations.utc_clock:
    class: Symfony\Component\Clock\NativeClock
    arguments:
      - 'utc'
  Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Time\UtcClock:
    arguments:
      - '@phpro_translations.utc_clock'
  Phpro\SuluTranslationsBundle\Domain\Time\Clock: '@Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Time\UtcClock'
