services:
  Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Writer:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Command\WriteHandler'

  Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Loader:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Repository\TranslationRepository'

  Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Remover:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Domain\Command\DeleteHandler'

  Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\DatabaseProviderFactory:
    arguments:
      - '@Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Writer'
      - '@Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Loader'
      - '@Phpro\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Remover'
      - '@Doctrine\Persistence\ManagerRegistry'
    tags:
      - { name: 'translation.provider_factory' }